#!/usr/bin/env bash
set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── Requirements ─────────────────────────────────────────────────
info "Checking requirements..."

if [[ "$(id -u)" -ne 0 ]]; then
  error "This installer must be run as root. Try: sudo bash install.sh"
fi

if ! grep -qi ubuntu /etc/os-release 2>/dev/null; then
  error "This installer only supports Ubuntu. Detected: $(grep '^PRETTY_NAME' /etc/os-release | cut -d= -f2)"
fi

UBUNTU_VERSION=$(grep '^VERSION_ID' /etc/os-release | tr -d '"' | cut -d= -f2)
info "Ubuntu $UBUNTU_VERSION detected."

# ── Directories ───────────────────────────────────────────────────
INSTALL_DIR="${INSTALL_DIR:-/opt/infra-panel}"
BACKUP_DIR="${BACKUP_DIR:-/var/backups/infra-panel}"
DATA_DIR="${DATA_DIR:-/var/lib/infra-panel}"

info "Creating directories..."
mkdir -p "$INSTALL_DIR" "$BACKUP_DIR" "$DATA_DIR/postgres" "$DATA_DIR/redis"
success "Directories created."

# ── System packages ───────────────────────────────────────────────
info "Updating package lists..."
apt-get update -qq

# ── Docker ────────────────────────────────────────────────────────
if command -v docker &>/dev/null; then
  success "Docker already installed: $(docker --version)"
else
  info "Installing Docker..."
  apt-get install -y -qq ca-certificates curl gnupg lsb-release

  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg

  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list

  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  systemctl enable --now docker
  success "Docker installed: $(docker --version)"
fi

# ── Nginx ─────────────────────────────────────────────────────────
if command -v nginx &>/dev/null; then
  success "Nginx already installed: $(nginx -v 2>&1)"
else
  info "Installing Nginx..."
  apt-get install -y -qq nginx
  systemctl enable --now nginx
  success "Nginx installed: $(nginx -v 2>&1)"
fi

NGINX_SITES_DIR="/etc/nginx/sites-available/infra-panel"
mkdir -p "$NGINX_SITES_DIR"

# ── Certbot ───────────────────────────────────────────────────────
if command -v certbot &>/dev/null; then
  success "Certbot already installed: $(certbot --version)"
else
  info "Installing Certbot..."
  apt-get install -y -qq snapd
  snap install --classic certbot 2>/dev/null || apt-get install -y -qq certbot python3-certbot-nginx
  ln -sf /snap/bin/certbot /usr/bin/certbot 2>/dev/null || true
  success "Certbot installed: $(certbot --version)"
fi

# ── UFW ───────────────────────────────────────────────────────────
if ! command -v ufw &>/dev/null; then
  info "Installing UFW..."
  apt-get install -y -qq ufw
fi

ufw allow 22/tcp  2>/dev/null || true
ufw allow 80/tcp  2>/dev/null || true
ufw allow 443/tcp 2>/dev/null || true
ufw --force enable 2>/dev/null || true
success "UFW configured (SSH, HTTP, HTTPS allowed)."

# ── PostgreSQL client ─────────────────────────────────────────────
if command -v psql &>/dev/null; then
  success "PostgreSQL client already installed."
else
  info "Installing PostgreSQL client..."
  apt-get install -y -qq postgresql-client
  success "PostgreSQL client installed."
fi

# ── Generate .env file ────────────────────────────────────────────
ENV_FILE="$INSTALL_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists at $ENV_FILE -- skipping generation."
  # Read existing DB creds so Docker Compose vars stay consistent
  DB_USER=$(grep '^POSTGRES_USER=' "$ENV_FILE" | cut -d= -f2 || echo "infrapanel")
  DB_PASSWORD=$(grep '^POSTGRES_PASSWORD=' "$ENV_FILE" | cut -d= -f2 || openssl rand -hex 16)
  DB_NAME=$(grep '^POSTGRES_DB=' "$ENV_FILE" | cut -d= -f2 || echo "infrapanel")
  REDIS_PASSWORD=$(grep '^REDIS_PASSWORD=' "$ENV_FILE" | cut -d= -f2 || openssl rand -hex 16)
else
  info "Generating .env file..."

  JWT_SECRET=$(openssl rand -hex 32)
  DB_PASSWORD=$(openssl rand -hex 16)
  DB_USER="infrapanel"
  DB_NAME="infrapanel"
  REDIS_PASSWORD=$(openssl rand -hex 16)

  cat > "$ENV_FILE" <<EOF
# infra-panel environment -- generated by installer
NODE_ENV=production

# Database
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=${DB_NAME}
DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379

# Auth
JWT_SECRET=${JWT_SECRET}
JWT_ACCESS_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# API
API_PORT=3001
API_HOST=0.0.0.0
CORS_ORIGIN=http://localhost:3000

# Web
NEXT_PUBLIC_API_URL=http://localhost:3001

# Paths
NGINX_SITES_DIR=${NGINX_SITES_DIR}
BACKUP_DIR=${BACKUP_DIR}
EOF

  chmod 600 "$ENV_FILE"
  success ".env generated at $ENV_FILE"
fi

# ── Copy panel files ───────────────────────────────────────────────
info "Copying panel files to $INSTALL_DIR..."
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

if [[ "$(realpath "$REPO_ROOT")" != "$(realpath "$INSTALL_DIR")" ]]; then
  # Exclude .env so the generated file is never overwritten by the repo copy
  rsync -a --exclude=node_modules --exclude=.git --exclude='*.log' --exclude='.env' \
    "$REPO_ROOT/" "$INSTALL_DIR/" 2>/dev/null || {
      cp -r "$REPO_ROOT/." "$INSTALL_DIR/"
      rm -f "$INSTALL_DIR/.env"
    }
  success "Files copied."
else
  success "Running in-place at $INSTALL_DIR -- skipping file copy."
fi

# ── Install Node.js + pnpm ────────────────────────────────────────
export NVM_DIR="$HOME/.nvm"

# nvm uses unbound variables internally -- must disable -u around all nvm calls
set +u

if [[ ! -d "$NVM_DIR" ]]; then
  info "Installing nvm..."
  curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
fi

# shellcheck source=/dev/null
source "$NVM_DIR/nvm.sh"

if ! command -v node &>/dev/null; then
  info "Installing Node.js LTS..."
  nvm install --lts
fi

nvm use --lts

if ! command -v pnpm &>/dev/null; then
  info "Installing pnpm..."
  npm install -g pnpm
fi

set -u

success "Node $(node -v) and pnpm $(pnpm -v) ready."

NODE_BIN="$(command -v node)"
info "Using node at: $NODE_BIN"

# ── Install dependencies + build ──────────────────────────────────
cd "$INSTALL_DIR"

info "Installing dependencies..."
pnpm install

info "Building panel..."
pnpm build

success "Panel built."

# ── Systemd services ──────────────────────────────────────────────
info "Installing systemd services..."

cat > /etc/systemd/system/infra-panel-api.service <<UNIT
[Unit]
Description=infra-panel API server
After=network.target docker.service
Requires=docker.service

[Service]
Type=simple
User=root
WorkingDirectory=${INSTALL_DIR}/apps/api
EnvironmentFile=${ENV_FILE}
ExecStart=${NODE_BIN} dist/index.js
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT

cat > /etc/systemd/system/infra-panel-web.service <<UNIT
[Unit]
Description=infra-panel Web server
After=infra-panel-api.service

[Service]
Type=simple
User=root
WorkingDirectory=${INSTALL_DIR}/apps/web
EnvironmentFile=${ENV_FILE}
ExecStart=${NODE_BIN} .next/standalone/server.js
Restart=on-failure
RestartSec=5
Environment=PORT=3000

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable infra-panel-api infra-panel-web
success "Systemd services installed."

# ── Start database containers ─────────────────────────────────────
info "Starting PostgreSQL and Redis containers..."

# Tear down any previous infra-panel containers
cd "$INSTALL_DIR"
docker compose --env-file "$ENV_FILE" down 2>/dev/null || true

# Stop any native services that may be holding ports 5432 / 6379
for svc in redis redis-server redis-sentinel postgresql postgresql-* pg_ctlcluster; do
  systemctl stop "$svc" 2>/dev/null || true
  systemctl disable "$svc" 2>/dev/null || true
done
# Last resort: kill anything still bound to those ports
fuser -k 5432/tcp 2>/dev/null || true
fuser -k 6379/tcp 2>/dev/null || true
sleep 1

docker compose --env-file "$ENV_FILE" up postgres redis -d

info "Waiting for PostgreSQL to be healthy..."
PG_READY=false
for i in $(seq 1 30); do
  if docker compose ps postgres 2>/dev/null | grep -q "healthy"; then
    PG_READY=true
    success "PostgreSQL is healthy."
    break
  fi
  sleep 2
done

if [[ "$PG_READY" != "true" ]]; then
  warn "PostgreSQL did not become healthy in time."
  warn "Fix with: docker compose logs postgres"
  warn "Then run: cd $INSTALL_DIR && pnpm db:generate && pnpm db:migrate"
else
  # ── Run database migrations ───────────────────────────────────────
  info "Generating and applying database migrations..."
  set -a; source "$ENV_FILE"; set +a
  cd "$INSTALL_DIR/packages/database"
  pnpm db:generate
  pnpm db:migrate
  cd "$INSTALL_DIR"
  success "Database migrations applied."
fi

# ── Start panel services ──────────────────────────────────────────
systemctl start infra-panel-api infra-panel-web
success "Panel services started."

# ── Verification ──────────────────────────────────────────────────
info "Verifying services..."
sleep 5

if curl -sf http://localhost:3001/api/health &>/dev/null; then
  success "API is reachable at http://localhost:3001"
else
  warn "API health check failed -- check: journalctl -u infra-panel-api -n 50"
fi

if curl -sf http://localhost:3000 &>/dev/null; then
  success "Web UI is reachable at http://localhost:3000"
else
  warn "Web UI not yet ready -- check: journalctl -u infra-panel-web -n 50"
fi

# ── Done ──────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  infra-panel installation complete!    ${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "  Web UI : http://localhost:3000"
echo "  API    : http://localhost:3001"
echo ""
echo "  .env   : $ENV_FILE"
echo "  Data   : $DATA_DIR"
echo "  Backups: $BACKUP_DIR"
echo ""
echo "  First run: open http://localhost:3000/setup to create your admin account."
echo ""
